variables:
  SolutionBaseName: 'dfc-composite-shell-moc-twocol'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:
 - task: gittools.gitversion.gitversion-task.GitVersion@4
   displayName: GitVersion
   inputs:
     preferBundledVersion: false
 - task: NuGetToolInstaller@0
   displayName: 'Use NuGet 4.3.0'
 - task: NuGetCommand@2
   displayName: 'NuGet restore ${{ variables.SolutionBaseName }}.sln'
   inputs:
     restoreSolution: '${{ variables.SolutionBaseName }}.sln'
 - task: DotNetCoreCLI@2
   displayName: 'dotnet build'
   inputs:
     command: 'build'
     arguments: '-o "$(build.artifactstagingdirectory)\Build\\"'
 - task: ArchiveFiles@2
   displayName: ArchiveFunctionApp
   inputs: 
     rootFolderOrFile: $(build.artifactstagingdirectory)\Build\
     archiveFile: $(build.artifactstagingdirectory)\DeploymentPackages\$(SolutionBaseName).zip
     includeRootFolder: false
 - task: CopyFiles@2
   displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Azure'
   inputs:
     sourceFolder: 'Resources'
     contents: '**'
     targetFolder: '$(build.artifactstagingdirectory)/Azure'
 - task: PublishBuildArtifacts@1
   displayName: 'Publish Artifact: ${{ variables.SolutionBaseName }}'
   inputs:
     pathtoPublish: $(build.artifactstagingdirectory)
     artifactName: ${{ variables.SolutionBaseName }}
     publishLocation: container